### ISSUE TITLE
Can't use cursor when creating project

### ISSUE THREAD

**Issue by pacome35220** [zetapush/zetapush#100]
**I'm submitting a ...** (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Scope** (check one with "x")
```
[ ] @zetapush/cli
[ ] @zetapush/cometd
[ ] @zetapush/client
[x] @zetapush/create
[ ] @zetapush/platform
[ ] @zetapush/worker
```

**Current behavior**
During the procedure of creating project with ```npx @zetapush/create celtia```, when i'm typing my developer login, the **cursor** is completely **offset to the right** of the text and is **unusable**.

**Expected behavior**

**Minimal reproduction of the problem with instructions**
```npx @zetapush/create celtia``` and try to use cursor with keyboard arrows.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Operating System:** Fedora 28
* **Node Version:** v8.11.3
* **Npm Version:** 5.6.0
* **@zetapush/\* Version:** any

**Comment by ghoullier** [comment]
RELATED ISSUES: https://github.com/hxoht/prompt-sync/issues/25
