### ISSUE TITLE
Non-explicit error message + non-relevant error information

### ISSUE THREAD

**Issue by pacome35220** [zetapush/zetapush#103]
**I'm submitting a ...** (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Scope** (check one with "x")
```
[x] @zetapush/cli
[ ] @zetapush/cometd
[ ] @zetapush/client
[ ] @zetapush/create
[ ] @zetapush/platform
[ ] @zetapush/worker
```

**Current behavior**
Non-explicit error message + non-relevant error information

**Expected behavior**
Beautiful help message

**Minimal reproduction of the problem with instructions**
- Download [issue.zip](https://github.com/zetapush/zetapush/files/2232468/issue.zip)
- Run ```npm install```
- Run ```npm run deploy```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Operating System:** Fedora 28
* **Node Version:** v8.11.3
* **Npm Version:** 5.6.0
* **@zetapush/\* Version:** any

**Comment by damienld22** [comment]
Unable to reproduce in 1.0.0
