### ISSUE TITLE
I need a cron service in my worker

### ISSUE THREAD

**Issue by pacome35220** [zetapush/zetapush#129]
**I'm submitting a ...** (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

**Scope** (check one with "x")
```
[ ] @zetapush/cli
[ ] @zetapush/cometd
[ ] @zetapush/client
[ ] @zetapush/create
[ ] @zetapush/platform
[x] @zetapush/worker
```

**Current behavior**
I'm working with external API with which I want to update data every 15 minutes. Like the title say, I need something like a **cron service** in my worker to call a method (like send in messaging service) every 15 minutes. To do this actually, I have to create a "fake" client in front/ directory, which call the worker method in a setInterval.

**Expected behavior**

Sometimes like "@cron(interval, callOnceAfter)" above the method concerned
- interval : in second,
- callOnceAfter : in second, if you want to call first time only after x second
 
For my use case : @cron(900, 0)

**Please tell us about your environment:**
* **@zetapush/\* Version:** 0.31.4

**Comment by damienld22** [comment]
A cron service already exists.
