### ISSUE TITLE
Split @zetapush/core client helper

### ISSUE THREAD

**Issue by ghoullier** [zetapush/zetapush#13]
Le code du [ClientHelper](https://github.com/zetapush/zetapush/blob/master/packages/core/src/client/helper.js) est devenu trop gros.

L'idée de ce refactoring est de séparer le code de cette classe en 4 parties distincts:

- src/client/helper/cometd-helper.js
- src/client/helper/lifecycle-helper.js
- src/client/helper/async-events.js
- src/client/helper/proxy-events.js

**cometd-helper.js** Gestion de la connection cometd et des methodes de souscriptions
**lifecycle-helper.js** Gestion des évènements lié au cycle de vie de la connection
**async-events.js** Gestion des méthode de création de service Async (Promise based)
**proxy-events.js** Gestion des méthode de création de service Proxy (Proxy based)

**Comment by damienld22** [comment]
Not a priority. The risk is too big about profit
