### ISSUE TITLE
feature request : provide a parsing method of .zetarc

### ISSUE THREAD

**Issue by pacome35220** [zetapush/zetapush#134]
**I'm submitting a ...** (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

**Scope** (check one with "x")
```
[ ] @zetapush/cli
[ ] @zetapush/cometd
[ ] @zetapush/client
[ ] @zetapush/create
[ ] @zetapush/platform
[x] @zetapush/worker
```

**Current behavior**
Actually, I clearly write appName and platformUrl in my angular webapp. I think it's not a good idea to write this clearly in the code (and so on git {hub / lab}). I think many developers will code a function that will parse `.zetarc` to get the JSON.

**What is the motivation / use case for changing the behavior?**
I think it might be a good idea to provide a method in `worker / index.ts` when we create a project with CLI, which **returns the element** corresponding to the **given key** in parameters, of .zetarc.

**Please tell us about your environment:**

* **Operating System:**
* **Node Version:** X.Y.Z
* **Npm Version:** X.Y.Z
* **@zetapush/\* Version:** X.Y.Z

**Comment by ghoullier** [comment]
Properties declared in .zetarc are injected in worker instance via environment variables
