### ISSUE TITLE
CLI print multiple times :  "Starting worker..."

### ISSUE THREAD

**Issue by pacome35220** [zetapush/zetapush#151]
**I'm submitting a ...** (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Scope** (check one with "x")
```
[ ] <root>
[x] @zetapush/cli
[ ] @zetapush/client
[ ] @zetapush/cometd
[ ] @zetapush/common
[ ] @zetapush/core
[ ] @zetapush/create
[ ] @zetapush/http-server
[ ] @zetapush/platform-legacy
[ ] @zetapush/testing
[ ] @zetapush/troubleshooting
[ ] @zetapush/user-management
[ ] @zetapush/worker
```

**Current behavior**
`zeta run` command print multiple times :  "Starting worker..."

**Expected behavior**

**Minimal reproduction of the problem with instructions**
```Console
npm run start
```
or

```Console
zeta run
```
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Operating System:**
* **Node Version:** X.Y.Z
* **Npm Version:** X.Y.Z
* **@zetapush/\* Version:** X.Y.Z

régression = croissant

**Comment by damienld22** [comment]
This issue will not be resolved as of now.
