### ISSUE TITLE
npm init using existing login/password displays a strange error

### ISSUE THREAD

**Issue by aurelien-baudet** [zetapush/zetapush#163]
**I'm submitting a ...** (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Scope** (check one with "x")
```
[ ] <root>
[ ] @zetapush/cli
[ ] @zetapush/client
[ ] @zetapush/cometd
[ ] @zetapush/common
[ ] @zetapush/core
[x] @zetapush/create
[ ] @zetapush/http-server
[ ] @zetapush/platform-legacy
[ ] @zetapush/testing
[ ] @zetapush/troubleshooting
[ ] @zetapush/user-management
[ ] @zetapush/worker
```

**Current behavior**

I already have a ZetaPush account. I execute the command:
`npm init @zetapush database-basic-key-value`

The application seems to be correctly created. However, a strange message that seems to be an error is displayed:

`$ npm init @zetapush database-basic-key-value`
> ../src/pos.cc: In function ‘void Method(const v8::FunctionCallbackInfo<v8::Value>&)’:
> ../src/pos.cc:243:6: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
>   int ret, row, col;
>       ^
> [SECURITY] Developer login ?:aurelien.baudet+celtia@zetapush.com
> [SECURITY] Developer password ?:********
> **[TODO] Catch 'createAccount' failure [ TypeError: Cannot read property 'code' of undefined
>       at network_1.fetch.then.catch (/home/aurelien/.npm/_npx/6423/lib/node_modules/@zetapush/create/node_modules/@zetapush/common/lib/createAccount.js:36:26)
>       at process._tickCallback (internal/process/next_tick.js:68:7) ] ‌**
> 
> Creating a new ZetaPush app in /mnt/data/developpement/zetapush-celtia/zetapush-examples/database-basic-key-value.

**Expected behavior**

Remove the strange message because I use my existing account, and the message says that it tries to create a new account.

**Minimal reproduction of the problem with instructions**

1. Create an account on ZetaPush
2. create a new project using `npm init @zetapush`

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Operating System:**
* **Node Version:** 10.8.0
* **Npm Version:** 6.2.0
* **@zetapush/\* Version:** 0.32.0

**Comment by ghoullier** [comment]
@aurelien-baudet  I'm not able to reproduce this problem with npm@5 and npm@6.

**Comment by damienld22** [comment]
Fixed
