### ISSUE TITLE
No exception thrown on connection failed

### ISSUE THREAD

**Issue by Naeoth** [zetapush/zetapush#164]
**I'm submitting a ...** (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Scope** (check one with "x")
```
[ ] <root>
[ ] @zetapush/cli
[x] @zetapush/client
[ ] @zetapush/cometd
[ ] @zetapush/common
[ ] @zetapush/core
[ ] @zetapush/create
[ ] @zetapush/http-server
[ ] @zetapush/platform-legacy
[ ] @zetapush/testing
[ ] @zetapush/troubleshooting
[x] @zetapush/user-management
[ ] @zetapush/worker
```

**Current behavior**

I tried to handle errors when the application is not connected to internet and the worker is not up.
In the case where there is no internet connection, I have an error which is thrown but there is no error message or something similar. Impossible to differentiate the caught exception.
In the other case, the application succeeded doesn't throw an exception even if the client is not connected.

**Expected behavior**

Throw an exception with an explicity name in both cases.

**Minimal reproduction of the problem with instructions**

```
const client = new SmartClient({
    platformUrl: 'https://celtia.zetapush.com/zbo/pub/business',
    appName: '',
  });
  client.setCredentials(credentials);
  try {
    await client.connect();
  } catch (e) {
    console.error(e);
  }
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Operating System:**
* **Node Version:** 10.8.0
* **Npm Version:** 6.4.1
* **@zetapush/\* Version:** 0.32.1

**Comment by ghoullier** [comment]
Hi @Naeoth!

This problem is already fixed by https://github.com/zetapush/zetapush/pull/160
Patched version will be released with 0.32.2.

**Comment by Naeoth** [comment]
Hello, the problem is fixed, I can catch error but the error codes are not explicit. If there is no internet connection I have an CONNECTION_FAILED with an empty cause and with a wrong login/ password, a CONNECTION_FAILED with 403::Handshake:Denied. It seems to be difficult to differentiate the errors.

Would a different code error for one error type be easier to handle ?

**Comment by ghoullier** [comment]
Hi @Naeoth !

We will support specfic error codes in a futur version of the server.

But, if there no internet connection you should have the following error response.
```json
{"code":"CONNECTION_FAILED","message":"Unable to connect to platform"}
```

**403::Handshake:Denied** message is returned by the platform when your tried to connect with invalid credentials.

**Comment by aurelien-baudet** [comment]
The reason is now handled. Waiting for approval of pull request : https://github.com/zetapush/zetapush/pull/188

I close this issue as original problem has been resolved and second problem will be merged soon.
