### ISSUE TITLE
Override the behavior of the connection token storage

### ISSUE THREAD

**Issue by damienld22** [zetapush/zetapush#205]
**I'm submitting a ...** (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

**Scope** (check one with "x")
```
[ ] <root>
[ ] @zetapush/cli
[x] @zetapush/client
[x] @zetapush/cometd
[ ] @zetapush/common
[ ] @zetapush/core
[ ] @zetapush/create
[ ] @zetapush/http-server
[ ] @zetapush/platform-legacy
[ ] @zetapush/testing
[ ] @zetapush/troubleshooting
[ ] @zetapush/user-management
[ ] @zetapush/worker
```

**Current behavior**

During a client connection, a token is stored in the local storage. 
I can override this behavior if my method to store / retrieve my token is synchronous.

**Expected behavior**

Override the behavior of token connection management to be able to store / retrieve the token with asynchronous method. (Ex : React Native case with react-native-storage)

**What is the motivation / use case for changing the behavior?**

React Native case 

**Please tell us about your environment:**

* **Operating System:**
* **Node Version:** X.Y.Z
* **Npm Version:** X.Y.Z
* **@zetapush/\* Version:** X.Y.Z

**Comment by ghoullier** [comment]
After some investigations we no longer plan to support built-in async persistence primitives in the core of ZetaPush Client in the short term due to breaking changes in top level Client API.

An async workflow can be easily implemented with a Client wrapping strategy:

```javascript
class AsyncClient {
 constructor(options) {
    this.client = new Client({
      ...options,
     authentication: () => this.getAuthentication()
   });
   this.credentials = null;
 }
 async connect() {
   // Get credentials from async persistence storage
   this.credentials = await this.asyncStorage.get();
   return this.client.connect()
 }
 async disconnect() {
   await this.asyncStorage.remove();
   return this.client.disconnect()
 }
 getAuthentication() {
   // Return ZetaPush Authentication based on red credentials
   return Authentication.simple(this.credentials)
 }
}
```
