### ISSUE TITLE
Support multiple/configurable artifacts

### ISSUE THREAD

**Issue by ghoullier** [zetapush/zetapush#231]
**I'm submitting a ...** (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

**Scope** (check one with "x")
```
[ ] <root>
[x] @zetapush/cli
[ ] @zetapush/client
[ ] @zetapush/cometd
[ ] @zetapush/common
[ ] @zetapush/core
[ ] @zetapush/create
[ ] @zetapush/http-server
[ ] @zetapush/platform-legacy
[ ] @zetapush/testing
[ ] @zetapush/troubleshooting
[ ] @zetapush/user-management
[x] @zetapush/worker
```

**Current behavior**
v0.35.* doesn't support multiple fronts/workers artifacts

**Expected behavior**
Futur cli have to support a configuration for artifacts to deploy.

Configurable file example

```json
{
  "workers": {
    "workerName1": "path/to/my/workerName1",
    "workerName2": "path/to/my/workerName2"
  },
  "fronts": {
    "frontName1": "path/to/my/frontName1",
    "frontName2": "path/to/my/frontName2"
  }
}
```

```console
zeta run --worker workerName2
```

**Need Discussions**

* Should we separate workers and fronts? 
* How can I run multiple worker in local mode

**Checklist**
- [ ] Support server publish format
- [ ] Update CLI
- [ ] Tests

**Please tell us about your environment:**

* **Operating System:**
* **Node Version:** X.Y.Z
* **Npm Version:** X.Y.Z
* **@zetapush/\* Version:** 0.35.*

**Comment by damienld22** [comment]
Feature reported
