### ISSUE TITLE
npm init @zetapush without project name as argument doesn't throw error

### ISSUE THREAD

**Issue by pacome35220** [zetapush/zetapush#251]
**I'm submitting a ...** (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Scope** (check one with "x")
```
[ ] <root>
[x] @zetapush/cli
[ ] @zetapush/client
[ ] @zetapush/cometd
[ ] @zetapush/common
[ ] @zetapush/core
[x] @zetapush/create
[ ] @zetapush/http-server
[ ] @zetapush/platform-legacy
[ ] @zetapush/testing
[ ] @zetapush/troubleshooting
[ ] @zetapush/user-management
[ ] @zetapush/worker
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Operating System:**
* **Node Version:** X.Y.Z
* **Npm Version:** X.Y.Z
* **@zetapush/\* Version:** X.Y.Z

**Comment by ghoullier** [comment]
Hello @pacome35220 .
This issue is already fixed via https://github.com/zetapush/zetapush/pull/245
