### ISSUE TITLE
Handle case of .zetarc in $HOME directory

### ISSUE THREAD

**Issue by damienld22** [zetapush/zetapush#290]
**I'm submitting a ...** (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

**Scope** (check one with "x")
```
[ ] <root>
[x] @zetapush/cli
[ ] @zetapush/client
[ ] @zetapush/cometd
[ ] @zetapush/common
[ ] @zetapush/core
[ ] @zetapush/create
[ ] @zetapush/http-server
[ ] @zetapush/platform-legacy
[ ] @zetapush/testing
[ ] @zetapush/troubleshooting
[ ] @zetapush/user-management
[ ] @zetapush/worker
```

**Current behavior**

I have a `.zetarc` file in my $HOME directory and no one in my application folder.
When I launch `zeta run` or `zeta push` a `.zetarc` file is created in my application with the same informations contained in the `.zetarc` file of my $HOME directory.

**Expected behavior**

No `.zetarc` file needs to be saved in my application folder if I use `.zetarc` of my $HOME directory.

**Minimal reproduction of the problem with instructions**

1) Create `.zetarc` in $HOME directory
2) Generate application with `npm init @zetapush myApp` anywhere
3) Remove `.zetarc` of your application
4) Launch `zeta run`

**What is the motivation / use case for changing the behavior?**

I don't want to have `.zetarc` in my application folder in this case.

**Please tell us about your environment:**

* **Operating System:** Linux
* **Node Version:** 11.0.0
* **Npm Version:** 6.4.1
* **@zetapush/\* Version:** 0.38.0-alpha.42b4a218

**Comment by aurelien-baudet** [comment]
It should already been handled by cosmiconfig
