### ISSUE TITLE
[npm init] Problem with password if login already exists

### ISSUE THREAD

**Issue by mikaelmorvan** [zetapush/zetapush#51]
When I create a new application with npm init @zetapush
If I'm already a registered curstomer: toto@zetapush.com, with a password: 123456
I can enter as a login: toto@zetapush.com and a false password: 1234567

The cli will initialize a new app without creating a new account but when I will launch the app with npm run start, the app will fail with a bad credential error.

What should the cli do ?
1) If the user exists, try to login to zbo
2) if the login fails, exit with error

**Comment by ghoullier** [comment]
This specific problem is not handle by npm init @zetapush or npx @zetapush/create command. If your credentials are invalid an error will be thrown on push or run command.
https://zetapush.github.io/documentation/#_wrong_login_or_password_account_03

**Comment by damienld22** [comment]
Fixed by #246
