### ISSUE TITLE
Cannot run any zeta command

### ISSUE THREAD

**Issue by gildas-lormeau** [zetapush/zetapush#54]
Currently, the doc says we can run the command `zeta` on the command line after having installed zetapush. However, since the CLI module is not installed as a global module, the command fails.
```
$ zeta run --serve-front
zeta: command not found
```

**Comment by ghoullier** [comment]
Hi!

According to the documentation, [6.1. From your terminal](https://zetapush.github.io/documentation/#_from_your_terminal)

```
npm run start is a script alias defined in the package.json file. The executed command under the hood is:
```

## Solution 1

Use aliases command **npm run start**  and **npm run deploy**.

## Solution 2

Update your PATH
```console
export PATH=./node_modules/.bin:$PATH
```

## Solution 3

Use npx tool (shipped with npm standard install)

```console
npx zeta <command>
```
