### ISSUE TITLE
The --serve-front switch is obsolete

### ISSUE THREAD

**Issue by gildas-lormeau** [zetapush/zetapush#57]
The [documentation](https://zetapush.github.io/documentation/#_from_your_terminal) says I can start the application with the command `npm run start -- --serve-front`. It does not work, the correct command is `npm run start -- --http-server`.

**Comment by ghoullier** [comment]
Which option name is the most relevant serve-front or http-serveur?

**Comment by gildas-lormeau** [comment]
Yep `http-serveur` à la française ! Problème réglé ;)

Maybe `--run-http-server` instead?

**Comment by ldiringer** [comment]
Shouldn't it be the default behaviour to run both front and worker processes?

**Comment by ghoullier** [comment]
@ldiringer Yes, **npm run start** alias can alias **zeta run --http-server**

**Comment by ghoullier** [comment]
CLOSED BY #76.
Next @zetapush/cli version (0.28) will no longer support --http-server. --server-front will be the new option name.
