### ISSUE TITLE
Unwanted logs in the console

### ISSUE THREAD

**Issue by gildas-lormeau** [zetapush/zetapush#61]
**I'm submitting a** (check one with "x")
```
[x] bug report
[ ] feature request
```

**Scope** (check one with "x")
```
[x] @zetapush/cli
[ ] @zetapush/cometd
[ ] @zetapush/core
[ ] @zetapush/create
[ ] @zetapush/platform
[x] @zetapush/worker
```
**Current behavior**
When calling an API method (`hello` in the example), the following logs are displayed in the shell by default.
```
WorkerInstance::dispatch { name: 'hello',
  namespace: '',
  parameters: undefined,
  requestId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  taskId: 'XXXXXXXXXX' }
WorkerInstance::result [...]
```
**Expected behavior**
These logs should not be displayed by default or they should be a way to disable them.

**Minimal reproduction of the problem with instructions**
Install the sample application, click the button, check the logs in the shell.

**What is the motivation / use case for changing the behavior?**
If the API returns for example a big String, it pollutes logs.

**Please tell us about your environment:**

* Operating System: Windows 10 Pro/WSL (Unbuntu 16.04.4 LTS)
* Node Version: 8.11.1
* Npm Version: 6.1.0

**Comment by ghoullier** [comment]
FIXED in v0.31.2
