### ISSUE TITLE
Fix the issue template

### ISSUE THREAD

**Issue by gildas-lormeau** [zetapush/zetapush#63]
**I'm submitting a ...** (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Scope** (check one with "x")
```
[ ] @zetapush/cli
[ ] @zetapush/cometd
[ ] @zetapush/core
[ ] @zetapush/create
[ ] @zetapush/platform
[ ] @zetapush/worker
```
**Current behavior**

There are some triple back-quotes  that are missing and also references to "angular" instead of "zetapush".

**Expected behavior**

We would not have to fix the template every time we post an issue.

**Minimal reproduction of the problem with instructions**

Create an issue, preview it.

**What is the motivation / use case for changing the behavior?**

We should not fix the template every time we post an issue.

**Please tell us about your environment:**

* **Operating System:** N/A
* **Node Version:** N/A
* **Npm Version:** N/A
* **@zetapush/ Version:** N/A

**Comment by gildas-lormeau** [comment]
The template of this bug can help to fix the default one ;).

**Comment by gildas-lormeau** [comment]
There's a missing typo, I guess `* **@zetapush/* Version:** X.Y.Z` should be replaced with `* **@zetapush/\* Version:** X.Y.Z`.

**Comment by ghoullier** [comment]
FXED by #66
