### ISSUE TITLE
How to create a JS project?

### ISSUE THREAD

**Issue by gildas-lormeau** [zetapush/zetapush#69]
**I'm submitting a ...** (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

**Scope** (check one with "x")
```
[x] @zetapush/cli
[ ] @zetapush/cometd
[ ] @zetapush/core
[ ] @zetapush/create
[ ] @zetapush/platform
[ ] @zetapush/worker
```

**Current behavior**

`npm init @zetapush <app-name>` creates a typescript project by default.

**Expected behavior**

How to create a JS project?

**Minimal reproduction of the problem with instructions**

N/A

**What is the motivation / use case for changing the behavior?**

Offer a way to create a JS project.

**Please tell us about your environment:**

* **Operating System:** N/A
* **Node Version:** N/A
* **Npm Version:** N/A
* **@angular/\* Version:** N/A

**Comment by dezmou** [comment]
You can add the flag to your npm init 
`npm init @zetapush <app-name> --javascript`

**Comment by gildas-lormeau** [comment]
Thanks! You should maybe add this useful information in the documentation.
