### ISSUE TITLE
npx @zetapush/create failed with unexpected error

### ISSUE THREAD

**Issue by pacome35220** [zetapush/zetapush#99]
**I'm submitting a ...** (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Scope** (check one with "x")
```
[ ] @zetapush/cli
[ ] @zetapush/cometd
[ ] @zetapush/client
[x] @zetapush/create
[ ] @zetapush/platform
[ ] @zetapush/worker
```

**Current behavior**

when i run ```npx @zetapush/create celtia```, the installation crashed on with error :
* "make: g++: Command not found"
And npx crashed with :
* "Error 127 `make` failed with exit code: 2"

**Expected behavior**
Explicit error message as : "g++ not found, please install g++ and restart installation"

**Minimal reproduction of the problem with instructions**
On Fedora 28, with ```npm -v``` : 5.6.0
```npx @zetapush/create celtia```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Operating System:** Fedora 28
* **Node Version:** v8.11.3
* **Npm Version:** 5.6.0
* **@zetapush/\* Version:** any

**Comment by pacome35220** [comment]
After installing g++ with my package manager (dnf on Fedora 28), the installation success but there are many many compile warning in .node-gyp directory :  I do not know if zetapush is in charged of this part of the installation.

**Comment by damienld22** [comment]
This compile warning in .node-gyp directory is not in charge of ZetaPush.
So I close this issue because I also added g++ as requirement in the documentation. https://doc.zetapush.com
